---
micronaut:
    application:
        name: books
                
#Uncomment to set server port
    server:
        port: 8080

---
datasources:
    default:
        url: jdbc:postgresql://localhost/postgres
        username: postgres
        password: app
        driverClassName: org.postgresql.Driver
        connectionTimeout: 4000
jpa:
  default:
    packages-to-scan:
        - 'org.acme.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          show_sql: true

